# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'
 source 'https://github.com/CocoaPods/Specs.git'
target 'Round' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Round
  pod 'Alamofire', '~> 3.4'
  pod 'ReactiveCocoa', '~> 4.2' # FRP 사용 위함
  pod 'AlamofireObjectMapper', '~> 3.0' #응답을 쉽게 스위프트 객체로 매핑하기 위한 도구.
  pod 'SwiftyJSON', '~> 2.3' #JSON사용을 쉽게 하기 위함
  pod 'RealmSwift' #쉽게 DB사용을 하기위한 프레임워크
  target 'RoundTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RoundUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
